=== VinuthaRavindranath/REST-Assured-API-Automation/target/classes/PetResponseSchema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "default": {},
  "title": "Root Schema",
  "required": [
    "id",
    "category",
    "name",
    "photoUrls",
    "tags",
    "status"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "default": 0,
      "title": "The id Schema",
      "examples": [
        2727
      ]
    },
    "category": {
      "type": "object",
      "default": {},
      "title": "The category Schema",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "default": 0,
          "title": "The id Schema",
          "examples": [
            11
          ]
        },
        "name": {
          "type": "string",
          "default": "",
          "title": "The name Schema",
          "examples": [
            "Lab"
          ]
        }
      },
      "examples": [{
        "id": 11,
        "name": "Lab"
      }]
    },
    "name": {
      "type": "string",
      "default": "",
      "title": "The name Schema",
      "examples": [
        "Simba"
      ]
    },
    "photoUrls": {
      "type": "array",
      "default": [],
      "title": "The photoUrls Schema",
      "items": {
        "type": "string",
        "default": "",
        "title": "A Schema",
        "examples": [
          "https://simba.com"
        ]
      },
      "examples": [
        [
          "https://simba.com"]
      ]
    },
    "tags": {
      "type": "array",
      "default": [],
      "title": "The tags Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "title": "The id Schema",
            "examples": [
              123,
              345,
              678
            ]
          },
          "name": {
            "type": "string",
            "title": "The name Schema",
            "examples": [
              "Simba",
              "Deno",
              "Fluffy"
            ]
          }
        },
        "examples": [{
          "id": 123,
          "name": "Simba"
        },
          {
            "id": 345,
            "name": "Deno"
          },
          {
            "id": 678,
            "name": "Fluffy"
          }]
      },
      "examples": [
        [{
          "id": 123,
          "name": "Simba"
        },
          {
            "id": 345,
            "name": "Deno"
          },
          {
            "id": 678,
            "name": "Fluffy"
          }]
      ]
    },
    "status": {
      "type": "string",
      "default": "",
      "title": "The status Schema",
      "examples": [
        "available"
      ]
    }
  },
  "examples": [{
    "id": 2727,
    "category": {
      "id": 11,
      "name": "Lab"
    },
    "name": "Simba",
    "photoUrls": [
      "https://simba.com"
    ],
    "tags": [{
      "id": 123,
      "name": "Simba"
    },
      {
        "id": 345,
        "name": "Deno"
      },
      {
        "id": 678,
        "name": "Fluffy"
      }],
    "status": "available"
  }]
}

=== VinuthaRavindranath/REST-Assured-API-Automation/src/main/java/Resources/PetPostRequestPayload.json
{
  "id": 2727,
  "category":
  {
    "id": 11,
    "name": "Lab"
  }
,
  "name": "Simba",
  "photoUrls": [
    "https://simba.com"
  ],
  "tags": [
    {
      "id": 123,
      "name": "Simba"
    },
    {
      "id": 345,
      "name": "Deno"
    },
    {
      "id": 678,
      "name": "Fluffy"
    }
  ],
  "status": "available"
}
